services:
  - type: web
    name: document-research-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: standard # Use standard plan for better resources
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-3.5-turbo
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_FOLDER
        value: /data
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: STATIC_FOLDER
        value: static
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
