services:
  - type: web
    name: document-research-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: standard # Use standard plan for better resources
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-3.5-turbo
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_FOLDER
        value: /data
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: STATIC_FOLDER
        value: static
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
